
experiment:
  name: compcos/utzappos
dataset:
  dataset: utzappos
  dataset_path: /data/sjh/dataset/ut-zappos
  splitname: compositional-split-natural
  open_world: false
  data_dir: ut-zap50k
model_params:
  model_type: CompCos
  
  dropout: true
  norm: true
  nlayers: 2
  relu: false
  fc_emb: 768,1024
  emb_dim: 300
  emb_type: glove
  word_embedding_root: /data/sjh/dataset/
  image_extractor: resnet18
  train_only: false
  static_inp: false
training:
  batch_size: 128
  load:
  device: cuda
  lr: 5.0e-05
  lrg: 0.001
  margin: 1.0
  cosine_scale: 50
  max_epochs: 300
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 64
  test_set: val
  topk: 1
  wd: 5.0e-05
  num_workers: 8
  update_image_features: false
  freeze_features: false
  epoch_max_margin: 100

others:
  bias: 1000.0
  clean_only: false
  clf_init: false
  composition: mlp_add
  cpu_eval: false
  cv_dir: logs/

  embed_rank: 64
  eval_type: dist
  eval_val_every: 1
  gcn_type: gcn
  gr_emb: d4096,d
  graph: false
  graph_init: null
  hard_masking: false
  lambda_ant: 0.0
  lambda_aux: 0.0
  lambda_axiom: 0
  lambda_cls_attr: 0
  lambda_cls_obj: 0
  lambda_comm: 0.0
  lambda_inv: 0.0
  lambda_sym: 0
  lambda_trip: 0

  nmods: 24

  num_negs: 1
  open_world: false
  pair_dropout: 0.0

  subset: false
  threshold: null
  threshold_trials: 50

  update_feasibility_every: 1

