DATASET:
  dataset_path: '/data/sjh/dataset/MITStates/release_dataset'
  name: 'mitstates'
  splitname: 'compositional-split-natural'

MODEL:
  config_name: 'mitstates-cot'
  model_type: 'CoT'
  load_checkpoint:

  img_emb_dim: 768
  img_emb_drop: 0.35

  wordembs: 'glove'
  wordemb_compose: 'obj-conditioned-cgqa'
  wordemb_compose_dropout: 0.2

  emb_dim: 300

  lambda_attn: 10.0
  attn_normalized: True

  classifier: 'cosine'
  cosine_cls_temp: 0.05

  w_loss_main: 1.0

  use_attr_loss: True
  w_loss_attr: 0.25

  use_obj_loss: True
  w_loss_obj: 0.25

  use_emb_pair_loss: True
  emb_loss_main: 0.1

  use_composed_pair_loss: True
  unseen_loss_ratio: 0.125
  seen_loss_ratio: 0.125

TRAIN:
  log_id: "This is the training process of CoT"
  log_dir: 'exp'
  checkpoint_dir: 'exp'
  num_workers: 4
  seed: 124

  batch_size: 128
  test_batch_size: 64

  finetune_backbone: True
  use_precomputed_features: False
  comb_features: False

  lr_word_embedding: 2.5e-6
  lr_encoder: 1e-5  
  lr: 1e-4
  wd: 5e-5

  disp_interval: 283
  save_every_epoch: 1
  eval_every_epoch: 1

  start_epoch: 1
  start_epoch_validate: 10
  max_epoch: 36
  final_max_epoch: 36

  decay_strategy: 'milestone' 
  decay_factor: 0.1
  aug_epoch: 24
  lr_decay_milestones: [23,30]

EVAL:
  topk: 1
